# Simple Netlify Configuration for NestJS Backend
# Use this if you want a minimal configuration

[build]
  command = "npm ci --production=false && npx prisma generate && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

# Production context
[context.production]
  command = "npm run build"

# Staging/preview context
[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "staging"

# Branch deploys
[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "staging"

# Functions directory
[functions]
  directory = "netlify/functions"

# Basic CORS headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Health check redirect
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
