# Netlify Configuration for NestJS Backend Application
[build]
  # Build command - ultra simple approach
  command = "npm install && npx prisma generate && npm run build"
  
  # Directory to publish (where the built files are located)
  publish = "dist"
  
  # Base directory for the build
  base = "."

# Build environment variables
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  # Public environment variables (safe to commit)
  NODE_ENV = "production"
  PORT = "3000"
  SOCKET_PORT = "3001"
  MAX_FILE_SIZE = "10485760"
  UPLOAD_DEST = "./uploads"
  JWT_EXPIRES_IN = "7d"

# Production deployment settings
[context.production]
  command = "npm install && npx prisma generate && npm run build"
  
  [context.production.environment]
    NODE_ENV = "production"

# Branch deploy settings (for feature branches)
[context.branch-deploy]
  command = "npm run build"
  
  [context.branch-deploy.environment]
    NODE_ENV = "staging"

# Deploy preview settings (for pull requests)
[context.deploy-preview]
  command = "npm run build"
  
  [context.deploy-preview.environment]
    NODE_ENV = "staging"

# Netlify Functions configuration (if you plan to use serverless functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers for security and CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API redirects to Netlify Functions (uncomment if using functions)
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# Health check redirect
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# Build plugins (add any Netlify plugins you need)
# [[plugins]]
#   package = "@netlify/plugin-name"

# Edge functions (uncomment if using Netlify Edge Functions)
# [[edge_functions]]
#   function = "auth"
#   path = "/api/auth/*"

# Build processing (uncomment if needed)
# [build.processing]
#   skip_processing = false

# Dev server settings for local development
[dev]
  command = "npm run start:dev"
  port = 3000
  publish = "dist"
  autoLaunch = false

# Note: Additional environment variables should be set in Netlify UI
# Sensitive values like DATABASE_URL, JWT_SECRET, etc. should never be committed

# Branch-specific settings
[context.staging]
  command = "npm run build"
  
  [context.staging.environment]
    NODE_ENV = "staging"

# Local development context
[context.dev]
  command = "npm run start:dev"
  
  [context.dev.environment]
    NODE_ENV = "development"
